### ISSUE TITLE
TypeError when adding package

### ISSUE THREAD

**Issue by jaypanares** [mizzao/meteor-partitioner#11]
Hi,

I'm trying to implement this package on a forked project.  After adding the package and running `meteor`, I get the following error when my app builds:

```
ERROR TypeError: Object #<Object> has no method 'isDirectUserSelector'
I20150703-10:32:20.972(0)?   at Object.userFindHook (/home/ubuntu/workspace/.meteor/local/build/programs/server/packages/mizzao_partitioner.js:195:15)
I20150703-10:32:20.972(0)?   at /home/ubuntu/workspace/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:568:24
I20150703-10:32:20.972(0)?   at Array.forEach (native)
I20150703-10:32:20.973(0)?   at Function._.each._.forEach (/home/ubuntu/workspace/.meteor/local/build/programs/server/packages/underscore.js:139:11)
I20150703-10:32:20.973(0)?   at Object.CollectionHooks.defineAdvice.self (/home/ubuntu/workspace/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:567:7)
I20150703-10:32:20.973(0)?   at Object.collection.(anonymous function) [as find] (/home/ubuntu/workspace/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:127:21)
I20150703-10:32:20.973(0)?   at [object Object]._.extend.find (/home/ubuntu/workspace/.meteor/local/build/programs/server/packages/mongo.js:3621:29)
I20150703-10:32:20.973(0)?   at Accounts.urls (/home/ubuntu/workspace/.meteor/local/build/programs/server/packages/accounts-base.js:1604:28)
I20150703-10:32:20.974(0)?   at /home/ubuntu/workspace/.meteor/local/build/programs/server/boot.js:229:5
```

Any reason for the error?  Does this conflict with another package?

**Comment by mizzao** [comment]
This was very likely the result of #2, where you defined `Helpers` somewhere in your app.

It should be fixed now, in 0.5.5. Would you give that a try?
